# Generated by Django 4.0 on 2022-05-27 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fruit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fruit', models.CharField(max_length=100)),
                ('Qunatity', models.IntegerField()),
                ('Calories', models.IntegerField()),
                ('Fat', models.FloatField()),
                ('Sodium', models.IntegerField()),
                ('Potasium', models.IntegerField()),
                ('Carbohydrates', models.IntegerField()),
                ('Dietary_Fiber', models.IntegerField()),
                ('Sugars', models.IntegerField()),
                ('Protein', models.IntegerField()),
                ('Image', models.ImageField(upload_to='image')),
            ],
        ),
    ]
